# Site settings
title: davis land audio blog
email: dland95@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  an audio blog by davis land. it is neat. listen and subscribe on itunes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://davisland.info" # the base hostname & protocol for your site
twitter_username: davisinternet

# Build settings
markdown: kramdown
